pipeline:
  tests:
    image: registry.niklasmh.no/niklasmh
    pull: true
    when:
      event: push
    commands:
      - cp -R /tmp/node_modules .
      - npm test -- --coverage

  build:
    image: registry.niklasmh.no/niklasmh
    pull: true
    when:
      event: push
      branch:
        include: [ master ]
    commands:
      - cp -R /tmp/node_modules .
      - npm run build

  deploy-dev:
    image: drillster/drone-rsync
    hosts: [ dev.niklasmh.no ]
    key: ${RSYNC_KEY}
    secrets: [ rsync_key ]
    target: /home/niklasmh/niklasmh-web
    when:
      status: success
      event: push
      branch: master
    script:
      - echo "Release ${DRONE_TAG} from branch ${DRONE_BRANCH}"
      - cd /home/niklasmh/niklasmh-web
      - docker-compose run build
      - docker-compose restart server

  deploy-prod:
    image: drillster/drone-rsync
    hosts: [ dev.niklasmh.no ]
    key: ${RSYNC_KEY}
    secrets: [ rsync_key ]
    target: /home/niklasmh/niklasmh-web
    when:
      status: success
      event: tag
    script:
      - echo "Release ${DRONE_TAG} from branch ${DRONE_BRANCH}"
      - cd /home/niklasmh/niklasmh-web
      - docker-compose run build
      - docker-compose restart server
