pipeline:
  tests:
    image: registry.niklasmh.no/niklasmh:1.0
    pull: true
    when:
      event: push
    commands:
      - cp -R /tmp/node_modules .
      - npm test -- --coverage

  deploy-dev:
    image: drillster/drone-rsync
    hosts: [ dev.niklasmh.no ]
    key: ${RSYNC_KEY}
    secrets: [ rsync_key ]
    target: /home/niklasmh/niklasmh-web
    when:
      status: success
      event: push
      branch: master
    script:
      - cd /home/niklasmh/niklasmh-web
      - docker-compose run build
      - docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --no-deps -d

  deploy-prod:
    image: drillster/drone-rsync
    hosts: [ dev.niklasmh.no ]
    key: ${RSYNC_KEY}
    secrets: [ rsync_key ]
    target: /home/niklasmh/niklasmh-web
    when:
      status: success
      event: tag
    script:
      - cd /home/niklasmh/niklasmh-web
      - docker-compose run build
      - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --no-deps -d
