pipeline:
  tests:
    image: registry.niklasmh.no/niklasmh
    when:
      event: push
    commands:
      - cd /srv/niklasmh
      - npm install --depth=0 --quiet
      - npm test -- --coverage

  deployment:
    image: plugins/ssh
    host: ci.niklasmh.no
    username: root
    port: 22
    when:
      event: tag
    script:
      - echo "Release ${DRONE_TAG} from branch ${DRONE_BRANCH}"
      - /home/niklasmh/deploy.sh
