pipeline:
  tests:
    image: registry.niklasmh.no/niklasmh:1.0
    pull: true
    when:
      event: push
    commands:
      - cp -R /tmp/node_modules .
      - npm install
      - npm test -- --coverage

  deploy-dev:
    image: drillster/drone-rsync
    hosts: [ dev.niklasmh.no ]
    key: ${RSYNC_KEY}
    secrets: [ rsync_key ]
    target: /home/niklasmh/niklasmh-web
    when:
      status: success
      event: push
      branch: master
    script:
      - cd /home/niklasmh/niklasmh-web
      - docker-compose run build
      - docker-compose build server
      - source .env.development.local
      - DOCKER_PORT=$DOCKER_PORT docker-compose up --no-deps --force-recreate -d server

  deploy-prod:
    image: drillster/drone-rsync
    hosts: [ dev.niklasmh.no ]
    key: ${RSYNC_KEY}
    secrets: [ rsync_key ]
    target: /home/niklasmh/niklasmh-web-prod
    when:
      status: success
      event: tag
    script:
      - cd /home/niklasmh/niklasmh-web-prod
      - docker-compose run build
      - docker-compose build server
      - source .env.production.local
      - DOCKER_PORT=$DOCKER_PORT docker-compose up --no-deps --force-recreate -d server
