version: '2'

services:
  build:
    image: registry.niklasmh.no/niklasmh
    command: ./deploy.sh
    volumes:
      - .:/srv/niklasmh:rw
  server:
    image: node:6
    command: node server.js
    restart: always
    ports:
      - ${DOCKER_PORT}:${PORT}
    volumes:
      - .:/srv/niklasmh:rw
    working_dir: /srv/niklasmh
