version: '2'

services:
  niklasmh:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run prod
    ports:
      - ${PORT}:5000
    volumes:
      - .:/srv/niklasmh/:rw
    working_dir: /srv/niklasmh
